### ISSUE TITLE
Error in google_analytics_account_list()

### ISSUE THREAD

**Issue by dhirsch** [MarkEdmondson1234/googleAnalyticsR_public#1]
Running `account_list <- google_analytics_account_list()` gives an error:

> request: https://www.googleapis.com/analytics/v3/management/accountSummaries/
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

Traceback shows:

> traceback()
7: stop("numbers of columns of arguments do not match")
6: rbind(deparse.level, ...)
5: f(init, x[[i]])
4: Reduce(rbind, listNameToDFCol(wp_prep, "accountId"))
3: data_parse_function(req$content, ...)
2: acc_sum()
1: google_analytics_account_list()

Retrieving actual data works fine, including the `google_analytics_meta()` function.

**Comment by MarkEdmondson1234** [comment]
Thanks! 

This package is very much a work in progress so for production I would use the others mentioned on the readme, but this feedback is useful for my testing so thanks for giving it a try :)

**Comment by dhirsch** [comment]
Since 'production' in just me pulling numbers down, I'll keep trying to use it and post any issues I run into. Thanks for developing all these packages.

**Comment by MarkEdmondson1234** [comment]
I've updated the version, but not directly fixed this - instead if it fails to parse it will give you the raw dataframe instead.

I couldn't replicate your issue, so I think your version is probably pulling data columns not present in my GA accounts - if you could paste here the result of `str(account_list)` then I or you can then use this to correct the data parse function.

**Comment by MarkEdmondson1234** [comment]
I think this is fixed now, it was due to GA mobile App accounts not having a URL to list when a URL was expected in the webProperty list.  Please test and reopen if it doesn't work.
