### ISSUE TITLE
multiple filters return error

### ISSUE THREAD

**Issue by mtoto** [MarkEdmondson1234/googleAnalyticsR_public#4]
gadata <- google_analytics(id = XXXXXX, 
                           start=start.date, end=end.date, 
                           metrics = c("uniquePageviews"), 
                           dimensions = c("pageTitle","date","channelGrouping"),
                           filters = c("ga:channelGrouping%3D%3DSocial","ga:channelGrouping%3D%3DDirect")
)

returns:

    Error in checkGoogleAPIError(req) : 
      JSON fetch error: Invalid value 'c("ga:channelGrouping==Social", "ga:channelGrouping==Direct").
      Values must match the following regular expression: 'ga:.+'

**Comment by MarkEdmondson1234** [comment]
Filters (And segments) are put in as characters as per the standard API docs, I don't parse it or anything as of yet. https://developers.google.com/analytics/devguides/reporting/core/v3/reference?hl=en#filters
