### ISSUE TITLE
samplingLevel = "WALK" -  error

### ISSUE THREAD

**Issue by mtoto** [MarkEdmondson1234/googleAnalyticsR_public#5]
The below query works and returns sampled results:

    start.date <-  "2015-05-01"
    end.date <- "2015-11-10"

    ga.data <- google_analytics(id = 93625103, 
                            start=start.date, end=end.date, 
                            metrics = c("uniquePageviews"), 
                            dimensions = c("pageTitle","date","channelGrouping"),
                            filters = "ga:pageTitle%3D%3DXXXXX,ga:pageTitle%3D%3DXXXXX;ga:country%3D%3DNetherlands;ga:deviceCategory%3D%3Ddesktop",
                            max=100000,)

However when I add samplingLevel = "WALK" to query I get:

    Request to profileId:  ()
    Error in if (x$kind == "analytics#gaData") { : argument is of length zero

**Comment by MarkEdmondson1234** [comment]
I just tried myself and it worked ok, so perhaps something account specific?

The queyr I tried that worked was:

    start.date <-  "2015-11-01"
    end.date <- "2015-11-10"

    ga.data <- google_analytics(id = accounts[26,'viewId'], 
                            start=start.date, end=end.date, 
                            metrics = c("uniquePageviews"), 
                            dimensions = c("pageTitle","date","channelGrouping"),
                            filters = "ga:pageTitle=~google,ga:pageTitle=~analytics;ga:deviceCategory==desktop;ga:country==denmark", samplingLevel = "WALK")

**Comment by MarkEdmondson1234** [comment]
Ahh got it - adding the max parameter broke it.  Its not necessary for walks so I'll put in a check to make setting it unnecessary too :)

**Comment by MarkEdmondson1234** [comment]
Try reloading the library and running the same command now.  I didn't get the same error exactly as you so I fixed something, but maybe not your issue specifically :)

**Comment by MarkEdmondson1234** [comment]
Please also make sure you have latest version of the supporting googleAuthR as well as this library, eg.

    devtools::install_github("MarkEdmondson1234/googleAuthR")
    devtools::install_github("MarkEdmondson1234/googleAnalytics_public")

**Comment by mtoto** [comment]
Ok, removed and reinstalled googleAuthR, now works!

**Comment by MarkEdmondson1234** [comment]
Great!
