### ISSUE TITLE
URLencode filters

### ISSUE THREAD

**Issue by JimmyG3** [MarkEdmondson1234/googleAnalyticsR_public#8]
When running a query with the filter "ga:pageTitle=@AT&T", it looks like the filter is not url encoded.  
I added this to line 15 of google_analytics and it appears to work:

    if (!is.null(filters)) {
        filters <- utils::URLencode(filters, reserved = TRUE)
        } 

There's probably a much more elegant solution out there, not sure I'm proficient enough to find it.

**Comment by MarkEdmondson1234** [comment]
Thanks Jimmy.  Your solution is elegant enough for me :)
